### ISSUE TITLE
Server problem

### ISSUE THREAD

**Issue by thepyroman13130** [MJRLegends/Space-Astronomy-2-Feedback-#227]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When i connect to the server with my friend all is working fine but when we broke a block, we can't collect the ressource and then there  is an  "invisible" block that we can't go throught.
With that bug, we can't even play.

### Steps to Reproduce Issue
1. Break a block

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
I don't have a crash log but every time i break a block the server console write:

[20:50:22] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$BreakEvent@27d89255:
java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174824_e(F)Lnet/minecraft/util/math/Vec3d;
at oreexcavation.shapes.ExcavateShape.getFacing(ExcavateShape.java:236) ~[ExcavateShape.class:?]
at oreexcavation.handlers.EventHandler.onBlockBreak(EventHandler.java:159) ~[EventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_554_EventHandler_onBlockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:742) [ForgeHooks.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:287) [lv.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) [lv.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) [me.class:?]
at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [ja.class:?]
at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [ja.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
[20:50:22] [Server thread/ERROR] [FML]: Index: 18 Listeners:
[20:50:22] [Server thread/ERROR] [FML]: 0: HIGH
[20:50:22] [Server thread/ERROR] [FML]: 1: ASM: class com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 2: NORMAL
[20:50:22] [Server thread/ERROR] [FML]: 3: ASM: class team.chisel.common.item.ChiselController onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 4: ASM: Block{null} onBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 5: ASM: slimeknights.tconstruct.tools.traits.TraitEstablished@7b119731 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 6: ASM: pcl.opensecurity.common.OSBreakEvent@298759b9 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 7: ASM: corail_pillar.handler.EventHandler@41d94103 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 8: ASM: li.cil.oc.common.EventHandler$@699c2f98 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 9: ASM: com.enderio.core.common.handlers.XPBoostHandler@c9095ac handleBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 10: ASM: CoroUtil.forge.EventHandlerForge@381ea995 breakBlockPlayer(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 11: ASM: mcjty.deepresonance.ForgeEventHandlers@6ac033a3 onBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 12: ASM: de.maxhenkel.gravestone.events.BlockEvents@30285e48 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 13: ASM: sblectric.lightningcraft.events.EntityItemEvents@538b3368 onUpgradedTileBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 14: ASM: p455w0rdslib.LibEvents@7d178fcb blockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 15: ASM: mcjty.rftools.ForgeEventHandlers@2713ac3d onBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 16: ASM: slimeknights.tconstruct.tools.TraitEvents@43e7908b blockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 17: LOWEST
[20:50:22] [Server thread/ERROR] [FML]: 18: ASM: oreexcavation.handlers.EventHandler@62178c89 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 19: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer@6019903e onBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/ERROR] [FML]: 20: ASM: blusunrize.immersiveengineering.common.EventHandler@4f5bcdd0 breakLast(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20:50:22] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174824_e(F)Lnet/minecraft/util/math/Vec3d;
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_45-internal]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174824_e(F)Lnet/minecraft/util/math/Vec3d;
at oreexcavation.shapes.ExcavateShape.getFacing(ExcavateShape.java:236) ~[ExcavateShape.class:?]
at oreexcavation.handlers.EventHandler.onBlockBreak(EventHandler.java:159) ~[EventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_554_EventHandler_onBlockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:742) ~[ForgeHooks.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:287) ~[lv.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_45-internal]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45-internal]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
... 5 more
**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.4.1

**Where did this bug happen:** 
Server
### Additional Information
Thx to help me and btw sorry for my english :s

**Comment by MJRLegends** [comment]
[PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
