### ISSUE TITLE
Crash with  MJRLEGENDSLIB 1.12.2

### ISSUE THREAD

**Issue by Cudis** [MJRLegends/Space-Astronomy-2-Feedback-#264]
I was made a mod pack and the problem it is the mod Mjrlegendslibs 1.12.2 which makes crash the game(set,play) somebody few tell me why and how settle(adjust) that please

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 6/26/18 9:50 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.NoSuchMethodError: com.mjr.mjrlegendslib.item.BasicSword.<init>(Lnet/minecraft/item/Item$ToolMaterial;Ljava/lang/String;)V
	at com.mjr.extraplanets.items.tools.ExtraPlanets_Tools.initializeTools(ExtraPlanets_Tools.java:144)
	at com.mjr.extraplanets.items.tools.ExtraPlanets_Tools.init(ExtraPlanets_Tools.java:134)
	at com.mjr.extraplanets.ExtraPlanets.preInit(ExtraPlanets.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 762822472 bytes (727 MB) / 1375731712 bytes (1312 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_D1 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version          | Source                                        | Signature                                |
	|:----- |:------------------- |:---------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2           | minecraft.jar                                 | None                                     |
	| UCH   | mcp                 | 9.42             | minecraft.jar                                 | None                                     |
	| UCH   | FML                 | 8.0.99.99        | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.4.2705     | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore       |                  | minecraft.jar                                 | None                                     |
	| UCH   | openmodscore        | 0.11.3           | minecraft.jar                                 | None                                     |
	| UCH   | appliedenergistics2 | rv5-alpha-8      | Applied-Energistics-2-Mod-1.12.2.jar          | None                                     |
	| UCH   | backpack            | 3.0.1            | Backpacks-Mod-1.12.2.jar                      | None                                     |
	| UCH   | betterfoliage       | 2.1.10           | BetterFoliage-MC1.12-2.1.10.jar               | None                                     |
	| UCH   | biomesoplenty       | 7.0.1.2361       | BiomesOPlenty-1.12.2-7.0.1.2361-universal.jar | None                                     |
	| UCH   | chameleon           | 1.12-4.1.3       | Chameleon-Library-1.12.jar                    | None                                     |
	| UCH   | customspawner       | 3.11.3           | CustomMobSpawner-3.11.3.jar                   | None                                     |
	| UCH   | mocreatures         | 12.0.3           | DrZharks MoCreatures Mod-12.0.3.jar           | None                                     |
	| UCH   | logicaldrops        | 0.9.4            | EM3R50N-LogicalDrops-1.12-14.21.1.2387.jar    | None                                     |
	| UCH   | mantle              | 1.12-1.3.2.24    | Mantle-1.12-1.3.2.24.jar                      | None                                     |
	| UCH   | jei                 | 4.8.5.159        | jei_1.12.2-4.8.5.159.jar                      | None                                     |
	| UCH   | tconstruct          | 1.12.2-2.9.0.55  | Tinkers-Construct-Mod-1.12.2.jar              | None                                     |
	| UCH   | galacticraftcore    | 4.0.1.177        | GalacticraftCore-1.12.2-4.0.1.177.jar         | None                                     |
	| UCH   | galacticraftplanets | 4.0.1.177        | Galacticraft-Planets-1.12.2-4.0.1.177.jar     | None                                     |
	| UCH   | mjrlegendslib       | 1.12.2-1.1.4     | MJRLegendsLib-1.12.2-1.1.4.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCEE  | extraplanets        | 1.12.2-0.1.5     | Extra-Planets-Mod-1.12.2.jar                  | None                                     |
	| UC    | extrautils2         | 1.0              | extrautils2-1.12-1.7.4.jar                    | None                                     |
	| UC    | journeymap          | 1.12.2-5.5.2     | JourneyMap-1.12.2.jar                         | None                                     |
	| UC    | mekanism            | 9.4.2            | Mekanism-Mod-Core-1.12.2.jar                  | None                                     |
	| UC    | mekanismgenerators  | 9.4.2            | Mekanism-Mod-Generators-1.12.2.jar            | None                                     |
	| UC    | mekanismtools       | 9.4.2            | Mekanism-Mod-Tools-1.12.2.jar                 | None                                     |
	| UC    | millenaire          | Millénaire 6.2.3 | Millenaire-Mod-Universal-1.12.2.jar           | None                                     |
	| UC    | minions             | 2.0.2            | Minions-Mod-1.12.2.jar                        | None                                     |
	| UC    | openmods            | 0.11.3           | OpenModsLib-1.12.2.jar                        | None                                     |
	| UC    | openblocks          | 1.7.3            | OpenBlocks-Mod-1.12.2.jar                     | None                                     |
	| UC    | storagedrawers      | 1.12-5.2.5       | Storage-Drawers-Mod-1.12.jar                  | None                                     |
	| UC    | torohealthmod       | 1.12.2-11        | ToroCrafts-Damage-Indicators-Mod-1.12.2.jar   | None                                     |
	| UC    | bspkrscore          | at_0.9           | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UC    | treecapitator       | at_0.9           | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UC    | veinminer           | 0.38.1           | Vein-Miner-Mod-1.12.jar                       | None                                     |
	| UC    | veinminermodsupport | 0.38.1           | Vein-Miner-Mod-1.12.jar                       | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2.jar)
  openmods.core.OpenModsClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.11' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: alpha rv5-alpha-8 for Forge 14.23.0.2491
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Kuda 1.11.2.zip
	OpenGlVersion: 4.6.0 NVIDIA 398.11
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Cudis** [comment]
@MJRLegends  pls HELP :'(

**Comment by MJRLegends** [comment]
This is the wrong place and second you have downloaded all your mods from a site that has stole them.

You might have to get the correct issue tracker too

**Comment by MJRLegends** [comment]
Checkout http://stopmodreposts.org/ as people shouldnt be allowed to repost mods on scam sites its illegal posting, And please download the browser plugins found near the bottom of http://stopmodreposts.org/get-involved/ to make sure your not helping these people!! #StopModReposts
