### ISSUE TITLE
Please Close. Corrupted vanilla MC. Likely not caused by Modpack installation, but minecraft itself. Forge calling empty class.

### ISSUE THREAD

**Issue by Error503Dev** [MJRLegends/Space-Astronomy-2-Feedback-#340]
### **Curseforge/MC Launcher issue, not modpack issue, I believe.**

Curseforge/MC Launcher got me a corrupt vanilla version in first place, which caused the crash on launch. 
I fixed it myself by replacing it manually with version of 1.10.2 I knew is not corrupt. Reinstalling a few times until it installs a non-corrupted version should work too.

> ### ---Issue Report---
> **(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**
> 
> **Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
> 
> Yes
> 
> ### Description of Issue
> Game crashed at Launch. Exit Code 0
> 
> ### Steps to Reproduce Issue
> 1. Install it on curseforge
> 2. launch it
> 
> **Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> Log link: https://pastebin.com/gjGjvwfA
> OR
> #### Just the important part of log:
> `[00:58:58] [main/ERROR]: Patcher expecting non-empty class data file for net.minecraft.entity.projectile.EntityThrowable, but received empty.
> [00:58:58] [main/ERROR]: Unable to launch
> java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.entity.projectile.EntityThrowable, but received empty, your vanilla jar may be corrupt.
> 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:170) ~[forge-1.10.2-12.18.3.2511.jar:?]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.entity.projectile.EntityThrowable, but received empty, your vanilla jar may be corrupt.
> 	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:114) ~[forge-1.10.2-12.18.3.2511.jar:?]
> 	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:77) ~[forge-1.10.2-12.18.3.2511.jar:?]
> 	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:217) ~[forge-1.10.2-12.18.3.2511.jar:?]
> 	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:191) ~[forge-1.10.2-12.18.3.2511.jar:?]
> 	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:160) ~[forge-1.10.2-12.18.3.2511.jar:?]
> 	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:189) ~[forge-1.10.2-12.18.3.2511.jar:?]
> 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:165) ~[forge-1.10.2-12.18.3.2511.jar:?]
> 	... 2 more`
> 
> 
> **Screenshots (if applicable):** 
> -
> **Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
> 1.5.7
> **Where did this bug happen:** [Single Player or Server]
> Single Player
> ### Additional Information
> -
>

**Comment by Error503Dev** [comment]
Don't know if I fucked up automated transfer to some dev board by posting part of the log. But I thought one shall not do it just because the entire log is long af.
