### ISSUE TITLE
Version 1.2.5 crashes on start up to desktop

### ISSUE THREAD

**Issue by WhisperFire26** [MJRLegends/Space-Astronomy-2-Feedback-#93]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Unable to start modpack after updating to version 1.2.5

### Steps to Reproduce Issue
1. Click on Space Astronomy 2 on Twitch Launcher
2. Click "Play" on Minecraft Launcher
3. Wait a few seconds before application crashes to desktop with no error message

**Crash log/Log (if applicable):** No error message given

**Screenshots (if applicable):** N/A

**Version of Mod Pack using:** 1.2.5

**Where did this bug happen:** Loading client

### Additional Information
Updated on 8/21/2017 to version 1.2.5, crashes to desktop on start up with no error message. Minecraft does not load.

**Comment by MJRLegends** [comment]
Crash log????

**Comment by MJRLegends** [comment]
This sounds like a launcher issue so im closing this as its out of my hands

**Comment by MJRLegends** [comment]
Please post the latest.log and fml latest log and i will double check

**Comment by WhisperFire26** [comment]
**Latest.Log**

[23:13:32] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:13:32] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:13:32] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:13:32] [main/INFO]: Forge Mod Loader version 12.18.3.2422 for Minecraft 1.10.2 loading
[23:13:32] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Users\Ang\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
[23:13:32] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/INFO]: [AstralCore] Initialized.
[23:13:32] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.5-1.10.jar
[23:13:32] [main/WARN]: The coremod com.tterrag.blur.BlurPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod com.creativemd.littletiles.LittlePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod com.creativemd.littletiles.LittleLatePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/WARN]: The coremod pcl.opensecurity.util.SoundUnpack does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:32] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.10.2_HD_U_E3.jar
[23:13:32] [main/ERROR]: Coremod Transformer: Unable to class load the plugin coolsquid.packguard.asm.Transformer
java.lang.ClassNotFoundException: coolsquid.packguard.asm.Transformer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:564) [forge-1.10.2-12.18.3.2422.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:425) [forge-1.10.2-12.18.3.2422.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255) [forge-1.10.2-12.18.3.2422.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102) [forge-1.10.2-12.18.3.2422.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79) [forge-1.10.2-12.18.3.2422.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41) [forge-1.10.2-12.18.3.2422.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138) [forge-1.10.2-12.18.3.2422.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:13:32] [main/WARN]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:33] [main/WARN]: The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:33] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:33] [main/WARN]: The coremod shetiphian.core.asm.TweakPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:33] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:13:33] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[23:13:33] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[23:13:33] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:13:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:13:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:13:33] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[23:13:33] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[23:13:33] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[23:13:33] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
[23:13:33] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/C:/Users/Ang/Documents/Curse/Minecraft/Instances/Space%20Astronomy%202/mods/OptiFine_1.10.2_HD_U_E3.jar
[23:13:33] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: C:\Users\Ang\Documents\Curse\Minecraft\Instances\Space Astronomy 2\mods\OptiFine_1.10.2_HD_U_E3.jar
[23:13:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[23:13:34] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Finished data injection.
[23:13:34] [main/INFO]: Finished data injection.
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Loaded library EJML-core-0.26.jar.
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:101]: Successfully Registered Transformer
[23:13:34] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:294]: [Micdoodle8Core]: Patching game...
[23:13:34] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:294]: [Micdoodle8Core]: Patching game...
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:34] [main/INFO]: [pcl.opensecurity.util.SoundUnpack:load:23]: Extracting sounds from: assets/opensecurity/sounds/alarms/
[23:13:34] [main/INFO]: [pcl.opensecurity.util.SoundUnpack:load:35]: Extracting file: klaxon1.ogg
[23:13:34] [main/INFO]: [pcl.opensecurity.util.SoundUnpack:load:35]: Extracting file: klaxon2.ogg
[23:13:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:35] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:35] [main/INFO]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[23:13:35] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:13:35] [main/INFO]: [AstralTransformer] Loading patches...
[23:13:35] [main/INFO]: [AstralTransformer] Initialized! Loaded 6 class patches!
[23:13:35] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:35] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:35] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:35] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:35] [main/INFO]: Found runtime patcher net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Found runtime patcher com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Found runtime patcher com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher$onInit$1
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:13:36] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:13:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:13:36] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[23:13:36] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[23:13:36] [main/INFO]: Patching net.minecraft.client.Minecraft... (bcx)
[23:13:36] [main/INFO]: [AstralTransformer] Transforming bcx : net.minecraft.client.Minecraft with 1 patches!
[23:13:36] [main/INFO]: [AstralTransformer] Applied patch PATCHKEYBOARDEVENT
[23:13:36] [main/INFO]: [com.tterrag.blur.BlurTransformer:transform:30]: Transforming Class [net.minecraft.client.gui.GuiScreen], Method [drawWorldBackground]
[23:13:36] [main/INFO]: [com.tterrag.blur.BlurTransformer:transform:52]: Modifying GUI background darkness... 
[23:13:36] [main/INFO]: [com.tterrag.blur.BlurTransformer:transform:72]: Transforming net.minecraft.client.gui.GuiScreen Finished.
[23:13:36] [main/INFO]: Attempting: Injection of Run Particle Override into Entity.createRunningParticles
[23:13:36] [main/INFO]: Searching for: Entity.createRunningParticles (func_174808_Z)
[23:13:36] [main/INFO]: Found Method: Entity.createRunningParticles
[23:13:36] [main/INFO]: Injecting: Run Particle Override
[23:13:36] [main/INFO]: Patching net.minecraft.client.entity.EntityPlayerSP... (bnn)
[23:13:36] [main/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:52]: [littletiles] Patched net.minecraft.entity.player.EntityPlayer ...
[23:13:36] [main/INFO]: Transforming net.minecraft.entity.player.EntityPlayer finished, added func_184613_cA() overriding EntityLivingBase
[23:13:36] [main/INFO]: [AstralTransformer] Transforming sf : net.minecraft.entity.EntityLivingBase with 1 patches!
[23:13:36] [main/INFO]: [AstralTransformer] Applied patch PATCHKNOCKBACKEVENT
[23:13:36] [main/INFO]: Patching class net/minecraft/entity/EntityLivingBase
[23:13:36] [main/INFO]:    Patching method func_70617_f_()Z
[23:13:36] [main/INFO]: [pl.asie.foamfix.coremod.patches.ClassGetSimpleNamePatch$FFMethodVisitor:visitMethodInsn:49]: Replaced getSimpleName with getName
[23:13:36] [main/INFO]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:113]: Added METHOD: net.minecraft.world.World.func_191504_a
[23:13:36] [Client thread/INFO]: Patching class net/minecraft/server/MinecraftServer
[23:13:36] [Client thread/INFO]:    Patching method run()V
[23:13:36] [Client thread/INFO]: Setting user: WhisperFire26
[23:13:36] [Client thread/INFO]: Patching net.minecraft.block.Block... (akf)
[23:13:36] [Client thread/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:transform:38]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[23:13:36] [Client thread/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:transform:93]: Transforming net.minecraft.block.Block Finished.
[23:13:36] [Client thread/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:transform:38]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[23:13:37] [Client thread/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/Block
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:72) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:66) ~[GameData.class:?]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[ni.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:536) ~[kq.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:341) ~[bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.Block
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:72) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:66) ~[GameData.class:?]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[ni.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:536) ~[kq.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:341) ~[bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer team.chisel.ctm.client.asm.CTMTransformer@3982206a from coremod CTMCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253) ~[forge-1.10.2-12.18.3.2422.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:72) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:66) ~[GameData.class:?]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[ni.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:536) ~[kq.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:341) ~[bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassCastException: org.objectweb.asm.tree.MethodInsnNode cannot be cast to org.objectweb.asm.tree.VarInsnNode
	at team.chisel.ctm.client.asm.CTMTransformer.transform(CTMTransformer.java:58) ~[CTMTransformer.class:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249) ~[forge-1.10.2-12.18.3.2422.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:72) ~[GameData.class:?]
	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:66) ~[GameData.class:?]
	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[ni.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:536) ~[kq.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:341) ~[bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
[23:13:37] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:13:37] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:13:37] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[23:13:37] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[23:13:37] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:968)
[23:13:37] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:13:37] [Client thread/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MJRLegends** [comment]
Upload the files dont paste them here @WhisperFire26

**Comment by WhisperFire26** [comment]
The system will not allow me to upload the latest text file. I am unable to find the fml file

**Comment by MJRLegends** [comment]
Just upload it to a site or use pastebin.com its possible and easy to do

**Comment by WhisperFire26** [comment]
I just finished backing up my files and simply uninstalled and reinstalled the pack. It works fine now. Thanks for your quick response.
